//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_ref
    {
        public int api_id { get; set; }
        public string api_name { get; set; }
        public Nullable<short> api_type_id { get; set; }
        public Nullable<short> client_id { get; set; }
        public Nullable<short> application_id { get; set; }
        public string api_dev_url { get; set; }
        public string api_dev_version { get; set; }
        public string api_dev_metadata { get; set; }
        public string api_dev_int_url { get; set; }
        public string api_dev_int_version { get; set; }
        public string api_dev_int_metadata { get; set; }
        public string api_qa_url { get; set; }
        public string api_qa_version { get; set; }
        public string api_qa_metadata { get; set; }
        public string api_prod_url { get; set; }
        public string api_prod_version { get; set; }
        public string api_prod_metadata { get; set; }
        public string api_metadata { get; set; }
        public string api_comments { get; set; }
    }
}
