//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist_action_xref
    {
        public int checklist_action_xref_id { get; set; }
        public Nullable<int> checklist_action_id { get; set; }
        public int checklist_id { get; set; }
        public Nullable<short> status_id { get; set; }
        public string powershell_script { get; set; }
        public string powershell_script_execution_comments { get; set; }
        public Nullable<int> powershell_script_timedout { get; set; }
        public Nullable<short> priority_order { get; set; }
        public string comments { get; set; }
    }
}
