//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist_template_ref
    {
        public short checklist_template_id { get; set; }
        public string checklist_template_nm { get; set; }
        public Nullable<short> sub_type_id { get; set; }
    }
}
