//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_type_ref
    {
        public short config_type_id { get; set; }
        public string config_type_nm { get; set; }
        public Nullable<bool> is_codebase { get; set; }
    }
}
