//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration_ref
    {
        public int config_id { get; set; }
        public string config_nm { get; set; }
        public string config_key { get; set; }
        public string config_dev_value { get; set; }
        public string config_dev_int_value { get; set; }
        public string config_qa_value { get; set; }
        public string config_prod_value { get; set; }
        public Nullable<bool> is_pdf { get; set; }
        public Nullable<byte> pdfaction { get; set; }
        public Nullable<int> work_item_id { get; set; }
        public Nullable<short> config_type_id { get; set; }
        public Nullable<short> config_status_id { get; set; }
        public Nullable<short> application_id { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> created_dtm { get; set; }
        public string created_usr_id { get; set; }
        public Nullable<System.DateTime> modified_dtm { get; set; }
        public string modified_usr_id { get; set; }
    }
}
