//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment_type_ref
    {
        public short deployment_type_id { get; set; }
        public string deployment_type_nm { get; set; }
        public Nullable<bool> is_smp_deployment { get; set; }
        public Nullable<bool> is_jenkins_deployment { get; set; }
        public Nullable<bool> is_manual_deployment { get; set; }
        public Nullable<bool> is_other_deployment { get; set; }
    }
}
