//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_ref
    {
        public short inventory_id { get; set; }
        public string inventory_nm { get; set; }
        public Nullable<byte> deployment_environment_id { get; set; }
        public Nullable<short> server_type_id { get; set; }
        public Nullable<byte> deployment_mse_environment_id { get; set; }
        public Nullable<short> application_id { get; set; }
        public string port_number { get; set; }
        public Nullable<bool> is_https { get; set; }
        public string website_nm { get; set; }
        public string virtual_directory { get; set; }
        public string physical_path { get; set; }
        public string validation_interface { get; set; }
        public string auto_validation_url { get; set; }
        public string gtm_name { get; set; }
        public string vip_name { get; set; }
        public string metadata { get; set; }
        public string comments { get; set; }
    }
}
