//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class release_work_item_xref
    {
        public int release_work_item_id { get; set; }
        public Nullable<short> release_id { get; set; }
        public Nullable<int> work_item_id { get; set; }
        public string biz_validation_sql { get; set; }
        public string biz_validation_comments { get; set; }
        public Nullable<bool> is_biz_validation_required { get; set; }
        public string biz_validator_nm { get; set; }
        public Nullable<byte> biz_validation_status { get; set; }
    }
}
