//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class release_ref
    {
        public short release_id { get; set; }
        public string release_nm { get; set; }
        public string release_descr { get; set; }
        public Nullable<System.DateTime> release_dt { get; set; }
        public Nullable<short> release_notes_status_id { get; set; }
        public Nullable<short> it_validation_status_id { get; set; }
        public Nullable<short> status_id { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> created_dtm { get; set; }
        public string created_usr_id { get; set; }
        public Nullable<System.DateTime> modified_dtm { get; set; }
        public string modified_usr_id { get; set; }
    }
}
