//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class release_sprint_xref
    {
        public int release_sprint_id { get; set; }
        public Nullable<short> release_id { get; set; }
        public Nullable<short> sprint_id { get; set; }
    }
}
