//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfc_detail_ref
    {
        public int rfc_detail_id { get; set; }
        public Nullable<int> rfc_id { get; set; }
        public Nullable<byte> rfc_report_part_id { get; set; }
        public string rfc_detail_key { get; set; }
        public string rfc_detail_nm { get; set; }
    }
}
