//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfc_template_application_xref
    {
        public short rfc_template_application_id { get; set; }
        public Nullable<short> rfc_template_id { get; set; }
        public Nullable<short> application_id { get; set; }
        public string pdf_file_name { get; set; }
    }
}
