//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scope_ref
    {
        public short scope_id { get; set; }
        public string scope_nm { get; set; }
        public Nullable<bool> is_dev_int { get; set; }
        public Nullable<bool> is_qa { get; set; }
        public Nullable<bool> is_production { get; set; }
    }
}
