//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class server_ref
    {
        public short server_id { get; set; }
        public short server_type_id { get; set; }
        public string server_nm { get; set; }
        public Nullable<bool> is_dr { get; set; }
    }
}
