//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssrs_report_ref
    {
        public short ssrs_report_id { get; set; }
        public string ssrs_report_nm { get; set; }
        public Nullable<bool> is_scheduling { get; set; }
        public Nullable<short> scheduler_interval_minutes { get; set; }
        public Nullable<byte> scheduler_output_type { get; set; }
        public string scheduler_email_ids { get; set; }
        public Nullable<System.DateTime> scheduler_last_executed { get; set; }
        public string scheduler_dates { get; set; }
        public string comments { get; set; }
    }
}
