//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTrackerSol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_item_ref
    {
        public int work_item_id { get; set; }
        public string work_item_ext_id { get; set; }
        public string work_item_title { get; set; }
        public Nullable<short> sprint_id { get; set; }
        public Nullable<short> scope_id { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> created_dtm { get; set; }
        public string created_usr_id { get; set; }
        public Nullable<System.DateTime> modified_dtm { get; set; }
        public string modified_usr_id { get; set; }
    }
}
